import Phaser from 'phaser'
import { CircleButtonSvg, HomeSceneImage, IconWhiteSvg, SquareButtonSvg } from '../../types/shared-typed'

export default class PreScene extends Phaser.Scene {
  constructor() {
    super({ key: 'PreScene' })
  }
  IconWhiteSvgSvg

  preload() {
    this.load.image(HomeSceneImage.BACKGROUND, 'assets/images/backgrounds/home_scene_background.png')
    // load circle button
    this.load.svg(CircleButtonSvg.PINK, 'assets/images/buttons/circles/pink.svg')
    this.load.svg(CircleButtonSvg.SHADOW, 'assets/images/buttons/circles/shadow.svg')
    this.load.svg(CircleButtonSvg.SHADOW_BORDER, 'assets/images/buttons/circles/shadow.svg')
    this.load.svg(CircleButtonSvg.BLUE, 'assets/images/buttons/circles/blue.svg')
    this.load.svg(CircleButtonSvg.BORDEAUX, 'assets/images/buttons/circles/bordeaux.svg')
    this.load.svg(CircleButtonSvg.BROWN, 'assets/images/buttons/circles/brown.svg')
    this.load.svg(CircleButtonSvg.DARK, 'assets/images/buttons/circles/dark.svg')
    this.load.svg(CircleButtonSvg.GRAY, 'assets/images/buttons/circles/gray.svg')
    this.load.svg(CircleButtonSvg.GRAY_BLUE, 'assets/images/buttons/circles/gray_blue.svg')
    this.load.svg(CircleButtonSvg.GREEN, 'assets/images/buttons/circles/green.svg')
    this.load.svg(CircleButtonSvg.LIGHT, 'assets/images/buttons/circles/light.svg')
    this.load.svg(CircleButtonSvg.ORANGE, 'assets/images/buttons/circles/orange.svg')
    this.load.svg(CircleButtonSvg.PURPLE, 'assets/images/buttons/circles/purple.svg')
    this.load.svg(CircleButtonSvg.RED, 'assets/images/buttons/circles/red.svg')
    this.load.svg(CircleButtonSvg.TEAL, 'assets/images/buttons/circles/teal.svg')
    this.load.svg(CircleButtonSvg.VIOLET, 'assets/images/buttons/circles/violet.svg')
    this.load.svg(CircleButtonSvg.YELLOW, 'assets/images/buttons/circles/yellow.svg')
    this.load.svg(CircleButtonSvg.BLUE_BORDER, 'assets/images/buttons/circles/blue_border.svg')
    this.load.svg(CircleButtonSvg.PURPLE_BORDER, 'assets/images/buttons/circles/purple_border.svg')
    // load white icon
    this.load.svg(IconWhiteSvg.ALERT, 'assets/images/icon-white/alert.svg')
    this.load.svg(IconWhiteSvg.ALERT_BELL, 'assets/images/icon-white/alert_bell.svg')
    this.load.svg(IconWhiteSvg.ARROW_DOWN, 'assets/images/icon-white/arrow_down.svg')
    this.load.svg(IconWhiteSvg.ARROW_DOWN_LINE, 'assets/images/icon-white/arrow_down_line.svg')
    this.load.svg(IconWhiteSvg.ARROW_LEFT, 'assets/images/icon-white/arrow_left.svg')
    this.load.svg(IconWhiteSvg.ARROW_LEFT_LINE, 'assets/images/icon-white/arrow_left_line.svg')
    this.load.svg(IconWhiteSvg.ARROW_RIGHT, 'assets/images/icon-white/arrow_right.svg')
    this.load.svg(IconWhiteSvg.ARROW_RIGHT_LINE, 'assets/images/icon-white/arrow_right_line.svg')
    this.load.svg(IconWhiteSvg.ARROW_SIMPLE_DOWN, 'assets/images/icon-white/arrow_simple_down.svg')
    this.load.svg(IconWhiteSvg.ARROW_SIMPLE_LEFT, 'assets/images/icon-white/arrow_simple_left.svg')
    this.load.svg(IconWhiteSvg.ARROW_SIMPLE_RIGHT, 'assets/images/icon-white/arrow_simple_right.svg')
    this.load.svg(IconWhiteSvg.ARROW_SIMPLE_UP, 'assets/images/icon-white/arrow_simple_up.svg')
    this.load.svg(IconWhiteSvg.ARROW_THIN_LEFT, 'assets/images/icon-white/arrow_thin_left.svg')
    this.load.svg(IconWhiteSvg.ARROW_THIN_RIGHT, 'assets/images/icon-white/arrow_thin_right.svg')
    this.load.svg(IconWhiteSvg.ARROW_UP, 'assets/images/icon-white/arrow_up.svg')
    this.load.svg(IconWhiteSvg.ARROW_UP_LINE, 'assets/images/icon-white/arrow_up_line.svg')
    this.load.svg(IconWhiteSvg.BACKWARD, 'assets/images/icon-white/backward.svg')
    this.load.svg(IconWhiteSvg.BADGE, 'assets/images/icon-white/badge.svg')
    this.load.svg(IconWhiteSvg.CHAT, 'assets/images/icon-white/chat.svg')
    this.load.svg(IconWhiteSvg.CHECKMARK, 'assets/images/icon-white/checkmark.svg')
    this.load.svg(IconWhiteSvg.CHECKMARK_CARTOON, 'assets/images/icon-white/checkmark_cartoon.svg')
    this.load.svg(IconWhiteSvg.CLOUD, 'assets/images/icon-white/cloud.svg')
    this.load.svg(IconWhiteSvg.CROWN, 'assets/images/icon-white/crown.svg')
    this.load.svg(IconWhiteSvg.CUP, 'assets/images/icon-white/cup.svg')
    this.load.svg(IconWhiteSvg.DISCORD, 'assets/images/icon-white/discord.svg')
    this.load.svg(IconWhiteSvg.EQUAL, 'assets/images/icon-white/equal.svg')
    this.load.svg(IconWhiteSvg.FACEBOOK, 'assets/images/icon-white/facebook.svg')
    this.load.svg(IconWhiteSvg.FORWARD, 'assets/images/icon-white/forward.svg')
    this.load.svg(IconWhiteSvg.GIFT, 'assets/images/icon-white/gift.svg')
    this.load.svg(IconWhiteSvg.GLASS, 'assets/images/icon-white/glass.svg')
    this.load.svg(IconWhiteSvg.HEART, 'assets/images/icon-white/heart.svg')
    this.load.svg(IconWhiteSvg.HELP, 'assets/images/icon-white/help.svg')
    this.load.svg(IconWhiteSvg.HOME, 'assets/images/icon-white/home.svg')
    this.load.svg(IconWhiteSvg.INFO, 'assets/images/icon-white/info.svg')
    this.load.svg(IconWhiteSvg.INSTAGRAM, 'assets/images/icon-white/instagram.svg')
    this.load.svg(IconWhiteSvg.LENS, 'assets/images/icon-white/lens.svg')
    this.load.svg(IconWhiteSvg.LEVEL, 'assets/images/icon-white/level.svg')
    this.load.svg(IconWhiteSvg.LIST, 'assets/images/icon-white/list.svg')
    this.load.svg(IconWhiteSvg.LOCK, 'assets/images/icon-white/lock.svg')
    this.load.svg(IconWhiteSvg.MAIL, 'assets/images/icon-white/mail.svg')
    this.load.svg(IconWhiteSvg.MENU, 'assets/images/icon-white/menu.svg')
    this.load.svg(IconWhiteSvg.MUSIC, 'assets/images/icon-white/music.svg')
    this.load.svg(IconWhiteSvg.MUSIC_SINGLE, 'assets/images/icon-white/music_single.svg')
    this.load.svg(IconWhiteSvg.PAUSE, 'assets/images/icon-white/pause.svg')
    this.load.svg(IconWhiteSvg.PENCIL, 'assets/images/icon-white/pencil.svg')
    this.load.svg(IconWhiteSvg.PHOTO, 'assets/images/icon-white/photo.svg')
    this.load.svg(IconWhiteSvg.PLUS, 'assets/images/icon-white/plus.svg')
    this.load.svg(IconWhiteSvg.QUESTION_MARK, 'assets/images/icon-white/question_mark.svg')
    this.load.svg(IconWhiteSvg.QUESTION_MARK_BORDER, 'assets/images/icon-white/question_mark_border.svg')
    this.load.svg(IconWhiteSvg.QUIT, 'assets/images/icon-white/quit.svg')
    this.load.svg(IconWhiteSvg.RANKING, 'assets/images/icon-white/ranking.svg')
    this.load.svg(IconWhiteSvg.RANKING_NUMBERS, 'assets/images/icon-white/ranking_numbers.svg')
    this.load.svg(IconWhiteSvg.RATE, 'assets/images/icon-white/rate.svg')
    this.load.svg(IconWhiteSvg.REPEAT, 'assets/images/icon-white/repeat.svg')
    this.load.svg(IconWhiteSvg.SETTINGS, 'assets/images/icon-white/settings.svg')
    this.load.svg(IconWhiteSvg.SHARE, 'assets/images/icon-white/share.svg')
    this.load.svg(IconWhiteSvg.SHARING, 'assets/images/icon-white/sharing.svg')
    this.load.svg(IconWhiteSvg.SHOP, 'assets/images/icon-white/shop.svg')
    this.load.svg(IconWhiteSvg.SOUND, 'assets/images/icon-white/sound.svg')
    this.load.svg(IconWhiteSvg.SOUND_OFF, 'assets/images/icon-white/sound_off.svg')
    this.load.svg(IconWhiteSvg.SOUND_ON, 'assets/images/icon-white/sound_on.svg')
    this.load.svg(IconWhiteSvg.STAR, 'assets/images/icon-white/star.svg')
    this.load.svg(IconWhiteSvg.STICKER_STAR, 'assets/images/icon-white/sticker_star.svg')
    this.load.svg(IconWhiteSvg.STICKER_STAR_BORDER, 'assets/images/icon-white/sticker_star_border.svg')
    this.load.svg(IconWhiteSvg.STOP, 'assets/images/icon-white/stop.svg')
    this.load.svg(IconWhiteSvg.TIME, 'assets/images/icon-white/time.svg')
    this.load.svg(IconWhiteSvg.TWITTER, 'assets/images/icon-white/twitter.svg')
    this.load.svg(IconWhiteSvg.USER, 'assets/images/icon-white/user.svg')
    this.load.svg(IconWhiteSvg.USERS, 'assets/images/icon-white/users.svg')
    this.load.svg(IconWhiteSvg.USER_PLUS, 'assets/images/icon-white/user_plus.svg')
    this.load.svg(IconWhiteSvg.X_ICON, 'assets/images/icon-white/x_icon.svg')
    this.load.svg(IconWhiteSvg.X_ICON_ROUNDED, 'assets/images/icon-white/x_icon_rounded.svg')
    this.load.svg(IconWhiteSvg.YOUTUBE, 'assets/images/icon-white/youtube.svg')
    // load square button
    this.load.svg(SquareButtonSvg.BLUE_TEAL, 'assets/images/buttons/squares/blue_teal.svg')
    this.load.svg(SquareButtonSvg.BORDEAUX, 'assets/images/buttons/squares/bordeaux.svg')
    this.load.svg(SquareButtonSvg.BROWN, 'assets/images/buttons/squares/brown.svg')
    this.load.svg(SquareButtonSvg.DARK, 'assets/images/buttons/squares/dark.svg')
    this.load.svg(SquareButtonSvg.GRAY, 'assets/images/buttons/squares/gray.svg')
    this.load.svg(SquareButtonSvg.GRAY_BLUE, 'assets/images/buttons/squares/gray_blue.svg')
    this.load.svg(SquareButtonSvg.GREEN, 'assets/images/buttons/squares/green.svg')
    this.load.svg(SquareButtonSvg.LIGHT, 'assets/images/buttons/squares/light.svg')
    this.load.svg(SquareButtonSvg.NEUTRAL, 'assets/images/buttons/squares/neutral.svg')
    this.load.svg(SquareButtonSvg.ORANGE, 'assets/images/buttons/squares/orange.svg')
    this.load.svg(SquareButtonSvg.PINK, 'assets/images/buttons/squares/pink.svg')
    this.load.svg(SquareButtonSvg.PURPLE, 'assets/images/buttons/squares/purple.svg')
    this.load.svg(SquareButtonSvg.RED, 'assets/images/buttons/squares/red.svg')
    this.load.svg(SquareButtonSvg.TEAL, 'assets/images/buttons/squares/teal.svg')
    this.load.image(SquareButtonSvg.VIOLET, 'assets/images/buttons/squares/violet.svg')
    this.load.svg(SquareButtonSvg.YELLOW, 'assets/images/buttons/squares/yellow.svg')
    this.load.svg(SquareButtonSvg.SHADOW, 'assets/images/buttons/squares/shadow.svg')
  }

  create() {
    this.scene.start('MainScene')
  }
}
