import Phaser from 'phaser'
import { CircleButton, HomeSceneImage, IconWhite } from '../../types/shared-typed'

export default class PreScene extends Phaser.Scene {
  constructor() {
    super({ key: 'PreScene' })
  }

  preload() {
    this.load.image(HomeSceneImage.BACKGROUND, 'assets/images/backgrounds/home-scene-background.png')
    // load circle button
    this.load.svg(CircleButton.PINK, 'assets/images/buttons/circles/pink.svg')
    this.load.svg(CircleButton.SHADOW, 'assets/images/buttons/circles/shadow.svg')
    this.load.svg(CircleButton.PURPLE_BORDER, 'assets/images/buttons/circles/purple-border.svg')
    this.load.svg(CircleButton.SHADOW_BORDER, 'assets/images/buttons/circles/shadow-border.svg')
    this.load.svg(CircleButton.BLUE, 'assets/images/buttons/circles/blue.svg')
    this.load.svg(CircleButton.BORDEAUX, 'assets/images/buttons/circles/bordeaux.svg')
    this.load.svg(CircleButton.BROWN, 'assets/images/buttons/circles/brown.svg')
    this.load.svg(CircleButton.DARK, 'assets/images/buttons/circles/dark.svg')
    this.load.svg(CircleButton.GRAY, 'assets/images/buttons/circles/gray.svg')
    this.load.svg(CircleButton.GRAY_BLUE, 'assets/images/buttons/circles/gray-blue.svg')
    this.load.svg(CircleButton.GREEN, 'assets/images/buttons/circles/green.svg')
    this.load.svg(CircleButton.LIGHT, 'assets/images/buttons/circles/light.svg')
    this.load.svg(CircleButton.ORANGE, 'assets/images/buttons/circles/orange.svg')
    this.load.svg(CircleButton.PURPLE, 'assets/images/buttons/circles/purple.svg')
    this.load.svg(CircleButton.RED, 'assets/images/buttons/circles/red.svg')
    this.load.svg(CircleButton.TEAL, 'assets/images/buttons/circles/teal.svg')
    this.load.svg(CircleButton.VIOLET, 'assets/images/buttons/circles/violet.svg')
    this.load.svg(CircleButton.YELLOW, 'assets/images/buttons/circles/yellow.svg')
    // load white icon
    this.load.svg(IconWhite.ALERT, 'assets/images/icon-white/alert.svg')
    this.load.svg(IconWhite.ALERT_BELL, 'assets/images/icon-white/alert_bell.svg')
    this.load.svg(IconWhite.ARROW_DOWN, 'assets/images/icon-white/arrow_down.svg')
    this.load.svg(IconWhite.ARROW_DOWN_LINE, 'assets/images/icon-white/arrow_down_line.svg')
    this.load.svg(IconWhite.ARROW_LEFT, 'assets/images/icon-white/arrow_left.svg')
    this.load.svg(IconWhite.ARROW_LEFT_LINE, 'assets/images/icon-white/arrow_left_line.svg')
    this.load.svg(IconWhite.ARROW_RIGHT, 'assets/images/icon-white/arrow_right.svg')
    this.load.svg(IconWhite.ARROW_RIGHT_LINE, 'assets/images/icon-white/arrow_right_line.svg')
    this.load.svg(IconWhite.ARROW_SIMPLE_DOWN, 'assets/images/icon-white/arrow_simple_down.svg')
    this.load.svg(IconWhite.ARROW_SIMPLE_LEFT, 'assets/images/icon-white/arrow_simple_left.svg')
    this.load.svg(IconWhite.ARROW_SIMPLE_RIGHT, 'assets/images/icon-white/arrow_simple_right.svg')
    this.load.svg(IconWhite.ARROW_SIMPLE_UP, 'assets/images/icon-white/arrow_simple_up.svg')
    this.load.svg(IconWhite.ARROW_THIN_LEFT, 'assets/images/icon-white/arrow_thin_left.svg')
    this.load.svg(IconWhite.ARROW_THIN_RIGHT, 'assets/images/icon-white/arrow_thin_right.svg')
    this.load.svg(IconWhite.ARROW_UP, 'assets/images/icon-white/arrow_up.svg')
    this.load.svg(IconWhite.ARROW_UP_LINE, 'assets/images/icon-white/arrow_up_line.svg')
    this.load.svg(IconWhite.BACKWARD, 'assets/images/icon-white/backward.svg')
    this.load.svg(IconWhite.BADGE, 'assets/images/icon-white/badge.svg')
    this.load.svg(IconWhite.CHAT, 'assets/images/icon-white/chat.svg')
    this.load.svg(IconWhite.CHECKMARK, 'assets/images/icon-white/checkmark.svg')
    this.load.svg(IconWhite.CHECKMARK_CARTOON, 'assets/images/icon-white/checkmark_cartoon.svg')
    this.load.svg(IconWhite.CLOUD, 'assets/images/icon-white/cloud.svg')
    this.load.svg(IconWhite.CROWN, 'assets/images/icon-white/crown.svg')
    this.load.svg(IconWhite.CUP, 'assets/images/icon-white/cup.svg')
    this.load.svg(IconWhite.DISCORD, 'assets/images/icon-white/discord.svg')
    this.load.svg(IconWhite.EQUAL, 'assets/images/icon-white/equal.svg')
    this.load.svg(IconWhite.FACEBOOK, 'assets/images/icon-white/facebook.svg')
    this.load.svg(IconWhite.FORWARD, 'assets/images/icon-white/forward.svg')
    this.load.svg(IconWhite.GIFT, 'assets/images/icon-white/gift.svg')
    this.load.svg(IconWhite.GLASS, 'assets/images/icon-white/glass.svg')
    this.load.svg(IconWhite.HEART, 'assets/images/icon-white/heart.svg')
    this.load.svg(IconWhite.HELP, 'assets/images/icon-white/help.svg')
    this.load.svg(IconWhite.HOME, 'assets/images/icon-white/home.svg')
    this.load.svg(IconWhite.INFO, 'assets/images/icon-white/info.svg')
    this.load.svg(IconWhite.INSTAGRAM, 'assets/images/icon-white/instagram.svg')
    this.load.svg(IconWhite.LENS, 'assets/images/icon-white/lens.svg')
    this.load.svg(IconWhite.LEVEL, 'assets/images/icon-white/level.svg')
    this.load.svg(IconWhite.LIST, 'assets/images/icon-white/list.svg')
    this.load.svg(IconWhite.LOCK, 'assets/images/icon-white/lock.svg')
    this.load.svg(IconWhite.MAIL, 'assets/images/icon-white/mail.svg')
    this.load.svg(IconWhite.MENU, 'assets/images/icon-white/menu.svg')
    this.load.svg(IconWhite.MUSIC, 'assets/images/icon-white/music.svg')
    this.load.svg(IconWhite.MUSIC_SINGLE, 'assets/images/icon-white/music-single.svg')
    this.load.svg(IconWhite.PAUSE, 'assets/images/icon-white/pause.svg')
    this.load.svg(IconWhite.PENCIL, 'assets/images/icon-white/pencil.svg')
    this.load.svg(IconWhite.PHOTO, 'assets/images/icon-white/photo.svg')
    this.load.svg(IconWhite.PLUS, 'assets/images/icon-white/plus.svg')
    this.load.svg(IconWhite.QUESTION_MARK, 'assets/images/icon-white/question_mark.svg')
    this.load.svg(IconWhite.QUESTION_MARK_BORDER, 'assets/images/icon-white/question_mark_border.svg')
    this.load.svg(IconWhite.QUIT, 'assets/images/icon-white/quit.svg')
    this.load.svg(IconWhite.RANKING, 'assets/images/icon-white/ranking.svg')
    this.load.svg(IconWhite.RANKING_NUMBERS, 'assets/images/icon-white/ranking_numbers.svg')
    this.load.svg(IconWhite.RATE, 'assets/images/icon-white/rate.svg')
    this.load.svg(IconWhite.REPEAT, 'assets/images/icon-white/repeat.svg')
    this.load.svg(IconWhite.SETTINGS, 'assets/images/icon-white/settings.svg')
    this.load.svg(IconWhite.SHARE, 'assets/images/icon-white/share.svg')
    this.load.svg(IconWhite.SHARING, 'assets/images/icon-white/sharing.svg')
    this.load.svg(IconWhite.SHOP, 'assets/images/icon-white/shop.svg')
    this.load.svg(IconWhite.SOUND, 'assets/images/icon-white/sound.svg')
    this.load.svg(IconWhite.SOUND_OFF, 'assets/images/icon-white/sound_off.svg')
    this.load.svg(IconWhite.SOUND_ON, 'assets/images/icon-white/sound-on.svg')
    this.load.svg(IconWhite.STAR, 'assets/images/icon-white/star.svg')
    this.load.svg(IconWhite.STICKER_STAR, 'assets/images/icon-white/sticker_star.svg')
    this.load.svg(IconWhite.STICKER_STAR_BORDER, 'assets/images/icon-white/sticker_star_border.svg')
    this.load.svg(IconWhite.STOP, 'assets/images/icon-white/stop.svg')
    this.load.svg(IconWhite.TIME, 'assets/images/icon-white/time.svg')
    this.load.svg(IconWhite.TWITTER, 'assets/images/icon-white/twitter.svg')
    this.load.svg(IconWhite.USER, 'assets/images/icon-white/user.svg')
    this.load.svg(IconWhite.USERS, 'assets/images/icon-white/users.svg')
    this.load.svg(IconWhite.USER_PLUS, 'assets/images/icon-white/user_plus.svg')
    this.load.svg(IconWhite.X_ICON, 'assets/images/icon-white/x_icon.svg')
    this.load.svg(IconWhite.X_ICON_ROUNDED, 'assets/images/icon-white/x_icon_rounded.svg')
    this.load.svg(IconWhite.YOUTUBE, 'assets/images/icon-white/youtube.svg')
  }

  create() {
    this.scene.start('MainScene')
  }
}
